[package]
name = "rootjni"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }

[lib]
name = "rootjni"
crate-type = ["staticlib", "cdylib"]
#crate-type = ["dylib"]
